security:
  basic:
    enabled: false
  user:
    password: pass
    
management:
  security:
    enabled: true
  info:
   git:
     mode: full
  cloudfoundry:
    skip-ssl-validation: true

cook.special: Kim Chi4 (git-repo> application.yml)

key1: test1
key2: test2 
key3: test3
key4: test4
    
