spring:
  config:
    name: config-client
  profiles:
    active: dev
---
spring:
  profiles: dev
key1: devkey1
key2: devkey2
foo: devfoo
aaa: aaa
eureka.instance.hostname: b
---
spring:
  profiles: cloud
key1: cloudkey1
key2: cloudkey2
foo: cloudfoo
